name: ALP Smoke Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq (for config parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run ALP smoke test
        run: |
          chmod +x .cursor/scripts/alp-logger.sh || true
          chmod +x .cursor/scripts/alp-smoke.sh || true
          out=$( .cursor/scripts/alp-smoke.sh )
          echo "Output: $out"
          # Must produce a path-like filename
          test -n "$out"
          case "$out" in
            *.md) echo "Looks like a markdown log file";;
            *) echo "Unexpected output: $out"; exit 1;;
          esac
