name: Auto-enable auto-merge for Changesets PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
    inputs:
      pr:
        description: PR number (optional; defaults to latest Changesets PR)
        required: false
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  auto_enable_on_pr_events:
    if: github.event_name == 'pull_request_target' && startsWith(github.event.pull_request.title, 'Version Packages')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

  manual_enable_via_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Resolve PR number
        id: find
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const inputPr = core.getInput('pr');
            if (inputPr) {
              core.setOutput('pr', inputPr);
            } else {
              const { data: prs } = await github.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 30,
              });
              const match = prs.find(pr =>
                pr.title?.startsWith('Version Packages') ||
                pr.head?.ref?.startsWith('changeset-release/')
              );
              if (!match) core.setFailed('No open Changesets release PR found');
              else core.setOutput('pr', String(match.number));
            }
      - name: Enable auto-merge on resolved PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.find.outputs.pr }}
          merge-method: squash
