name: Verify Changeset Present

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  verify:
    name: Require a changeset (or allow skip label)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Check PR for changeset or skip label
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Fetch labels fresh (payload can be stale)
            const prLabels = await github.paginate(
              github.rest.issues.listLabelsOnIssue,
              { owner, repo, issue_number: pr.number, per_page: 100 }
            );
            const labels = prLabels.map(l => l.name.toLowerCase());
            const allowLabels = new Set(["skip-changeset", "meta/no-changeset"]);
            const hasSkip = labels.some(l => allowLabels.has(l));

            // List files in this PR and look for .changeset/*.md (excluding config.json)
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner, repo, pull_number: pr.number, per_page: 100 }
            );
            const hasChangeset = files.some(f => {
              const p = f.filename;
              return p.startsWith('.changeset/') && p.endsWith('.md');
            });

            // Docs-only fallback: allow docs-only PRs without explicit label
            const isDocsOnly = files.length > 0 && files.every(f => {
              const p = f.filename;
              const isMarkdown = /\.mdc?$/.test(p);
              const isChangelog = /^CHANGELOG\.md$/.test(p);
              const matchesDocs = /^docs\//.test(p) || /^README\.md$/.test(p) || isMarkdown;
              return matchesDocs && !(isMarkdown && isChangelog);
            });

            if (hasSkip || isDocsOnly) {
              core.notice("Changeset check skipped (override label or docs-only PR).");
              return;
            }

            if (!hasChangeset) {
              core.setFailed("No changeset found (.changeset/*.md). Add one via 'npx changeset' or apply the 'skip-changeset' label if intentionally skipped.");
            } else {
              core.info("Changeset detected.");
            }
