name: Automerge bot PRs

on:
  pull_request:
    types: [opened, labeled]

# Grant the workflow necessary permissions
permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    # Only run this job for specific bot users
    # For Dependabot, use `github.actor == 'dependabot[bot]'`
    # For other bots, replace with the correct bot username
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Approve bot PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr review "$PR_URL" --approve

      - name: Enable auto-merge for the bot PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge "$PR_URL" --auto --squash
