name: Changesets

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  status:
    name: Changesets status (PR)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i -D @changesets/changelog-github@^0.5.1
      - run: npx -y @changesets/cli@^2.27.9 changeset status --since=origin/main
        continue-on-error: true

  version-pr:
    name: Open/Update “Version Packages” PR
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i -D @changesets/changelog-github@^0.5.1
      - uses: changesets/action@v1
        with:
          version: node .github/scripts/version-and-sync.cjs
          commit: "chore(release): version packages"
          title: "Version Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
