name: Verify Changeset Present

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  verify:
    name: Require a changeset (or allow skip label)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check PR for changeset or skip label
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Allow an explicit override via label
            const labels = (pr.labels || []).map(l => l.name.toLowerCase());
            const allowLabels = new Set(["skip-changeset", "meta/no-changeset"]);
            const hasSkip = labels.some(l => allowLabels.has(l));

            // List files in this PR and look for .changeset/*.md (excluding config.json)
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner, repo, pull_number: pr.number, per_page: 100 }
            );
            const hasChangeset = files.some(f => {
              const p = f.filename;
              return p.startsWith('.changeset/') && p.endsWith('.md');
            });

            if (hasSkip) {
              core.notice("Changeset check skipped due to override label.");
              return;
            }

            if (!hasChangeset) {
              core.setFailed("No changeset found (.changeset/*.md). Add one via 'npx changeset' or apply the 'skip-changeset' label if intentionally skipped.");
            } else {
              core.info("Changeset detected.");
            }
