name: Changesets auto-merge

on:
  workflow_run:
    workflows: ["Changesets"]
    types: [completed]
  workflow_dispatch:
    inputs:
      pr:
        description: PR number (optional; defaults to latest Changesets PR)
        required: false
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve target PR
        id: find
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const input = core.getInput('pr');
            if (input) { core.setOutput('pr', String(Number(input))); return; }
            if (context.eventName === 'workflow_run' && context.payload.workflow_run?.conclusion !== 'success') {
              core.setFailed('Changesets workflow did not succeed');
              return;
            }
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 30,
            });
            const match = prs.find(pr => (
              (pr.title?.startsWith('Version Packages') || pr.head?.ref?.startsWith('changeset-release/')) &&
              pr.user?.login === 'github-actions[bot]'
            ));
            if (!match) { core.setFailed('No open Changesets release PR found'); return; }
            core.setOutput('pr', String(match.number));

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.find.outputs.pr }}
          merge-method: squash
