name: Suggest Changeset

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  suggest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Suggest adding a changeset when missing
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const labels = (pr.labels || []).map(l => l.name.toLowerCase());
            const allowLabels = new Set(["skip-changeset", "meta/no-changeset"]);
            const hasSkip = labels.some(l => allowLabels.has(l));

            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner, repo, pull_number: pr.number, per_page: 100 }
            );
            const hasChangeset = files.some(f => {
              const p = f.filename;
              return p.startsWith('.changeset/') && p.endsWith('.md');
            });

            if (hasChangeset || hasSkip) return;

            const body = [
              `Heads up @${pr.user.login}: this PR doesn't include a Changeset.`,
              '',
              'To add one:',
              '```bash',
              'npx changeset',
              'git add . && git commit -m "chore(changeset): add"',
              '```',
              '',
              'After merging, the bot will open a “Version Packages” PR; merge it to update CHANGELOG.md and VERSION.',
              '',
              'If intentionally skipping, add the `skip-changeset` label.'
            ].join('\n');

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr.number,
              body
            });
