name: Deterministic Outputs — Validate Artifacts

on:
  # pull_request:  # Disabled by default; enable to validate on PRs
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      paths:
        description: CSV of artifact paths (specs/plans/tasks)
        required: false
        default: "docs/specs/sample-feature-spec.md,docs/plans/sample-feature-plan.md,tasks/tasks-sample-feature.md"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run validator
        shell: bash
        run: |
          set -euo pipefail
          PATHS="${{ github.event.inputs.paths }}"
          if [ -z "$PATHS" ]; then
            PATHS="docs/specs/sample-feature-spec.md,docs/plans/sample-feature-plan.md,tasks/tasks-sample-feature.md"
          fi
          bash ./.cursor/scripts/validate-artifacts.sh --paths "$PATHS"
