name: Docs Validate

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs-validate.yml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs-validate.yml"

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure Glossary/Owner Map links on legacy ERDs (if any)
        run: |
          missing=$(grep -L "\[Links: Glossary\]" docs/erd-*.md || true)
          if [ -n "$missing" ]; then
            echo "ERDs missing Glossary/Owner Map links:" >&2
            echo "$missing" >&2
            exit 1
          fi
      - name: Verify project ERDs have tasks.md siblings (skip archive redirects)
        run: |
          errs=0
          while IFS= read -r -d '' erd; do
            dir=$(dirname "$erd")
            # Skip archive redirect ERDs
            if grep -q "^template:\s*project-lifecycle/archive-redirect" "$erd"; then
              continue
            fi
            if [ ! -f "$dir/tasks.md" ]; then
              echo "Missing tasks.md for $erd" >&2
              errs=1
            fi
          done < <(find docs/projects -type f -name erd.md -print0)
          if [ $errs -ne 0 ]; then exit 1; fi
      - name: Verify assistant-logs is gitignored
        run: |
          if ! grep -qx 'assistant-logs/' .gitignore; then
            echo "assistant-logs/ must be listed in .gitignore" >&2
            exit 1
          fi
      - name: Validate investigation project structure
        run: |
          # Find all investigation projects (those with >15 total .md files)
          for project in docs/projects/*/; do
            total_files=$(find "$project" -name "*.md" | wc -l | tr -d ' ')
            if [ "$total_files" -gt 15 ]; then
              echo "Validating structure: $project ($total_files files)"
              bash .cursor/scripts/validate-investigation-structure.sh "$project" || exit 1
            fi
          done
