name: Update Repository Health Badge

on:
  push:
    branches:
      - main
    paths:
      - ".cursor/scripts/**/*.sh"
      - ".cursor/rules/**/*.mdc"
      - ".github/workflows/**/*.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run health validation and update badge
        id: update-badge
        run: |
          # Make script executable if not already
          chmod +x .cursor/scripts/repo-health-badge.sh
          chmod +x .cursor/scripts/deep-rule-and-command-validate.sh

          # Generate workflow run URL for clickable badge
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Update badge with workflow link
          .cursor/scripts/repo-health-badge.sh --workflow-url "$WORKFLOW_URL"

      - name: Check for README badge changes
        id: check_changes
        run: |
          if git diff --quiet README.md; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update repository health badge [skip ci]"
          title: "chore: update repository health badge"
          body: |
            Automated health badge update from validation run.

            Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          add-paths: |
            README.md
          branch: chore/update-health-badge
          delete-branch: true
          labels: skip-changeset
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
