name: Update Repository Health Badge

on:
  push:
    branches:
      - main
    paths:
      - ".cursor/scripts/**/*.sh"
      - ".cursor/rules/**/*.mdc"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest
    environment: AUTO_MERGE_TOKEN
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
          fetch-depth: 0

      - name: Run health validation and update badge
        id: update-badge
        run: |
          # Make script executable if not already
          chmod +x .cursor/scripts/repo-health-badge.sh
          chmod +x .cursor/scripts/deep-rule-and-command-validate.sh

          # Generate workflow run URL for clickable badge
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Update badge with workflow link
          .cursor/scripts/repo-health-badge.sh --workflow-url "$WORKFLOW_URL"

      - name: Check for README badge changes
        id: check_changes
        run: |
          if git diff --quiet README.md; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create or Update Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        run: |
          chmod +x ./.cursor/scripts/pr-create-or-update.sh
          
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          BRANCH="chore/update-health-badge"
          
          # Ensure branch exists with changes
          git checkout -b "$BRANCH" || git checkout "$BRANCH"
          git add README.md
          git commit -m "chore: update repository health badge [skip ci]" || true
          git push -f origin "$BRANCH"
          
          ./.cursor/scripts/pr-create-or-update.sh \
            --title "chore: update repository health badge" \
            --body "Automated health badge update from validation run.

Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --title-pattern "chore: update repository health badge" \
            --branch-prefix "chore/update-health-badge" \
            --owner "$OWNER" \
            --repo "$REPO" \
            --head "$BRANCH" \
            --base main \
            --label "skip-changeset"
