name: Update Repository Health Badge

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run health validation and update badge
        id: update-badge
        run: |
          # Make script executable if not already
          chmod +x .cursor/scripts/repo-health-badge.sh
          chmod +x .cursor/scripts/deep-rule-and-command-validate.sh

          # Generate workflow run URL for clickable badge
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Update badge with workflow link
          .cursor/scripts/repo-health-badge.sh --workflow-url "$WORKFLOW_URL"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update repository health badge [skip ci]"
          title: "chore: update repository health badge"
          body: |
            Automated health badge update from validation run.
            
            Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: chore/update-health-badge
          delete-branch: true
          labels: skip-changeset
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
