name: Rules Validate

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  rules-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run rules validator
        shell: bash
        run: |
          bash ./.cursor/scripts/rules-validate.sh | cat
name: Rules Validation

on:
  pull_request:
    paths:
      - ".cursor/rules/**"
      - ".cursor/scripts/**"
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up shell
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bash

      - name: Run rules validator
        run: |
          chmod +x ./.cursor/scripts/rules-validate.sh
          ./.cursor/scripts/rules-validate.sh
